# ===============================================================
# WARNING
# This file is not functional yet. Will be implemented later
# ===============================================================
repository:
  name: Brahmatruti/.dotfiles
  origin: git@github.com:Brahmatruti/.dotfiles.git
  raw: https://raw.githubusercontent.com/Brahmatruti/.dotfiles/main/

download:
  tarball: https://github.com/Brahmatruti/.dotfiles/tarball/main
  zip: https://github.com/Brahmatruti/.dotfiles/archive/main.zip
